# Generated by Django 2.0.2 on 2018-04-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogbuifyscrumy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumyuser',
            name='role',
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='password',
            field=models.TextField(default='1234'),
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='role_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ogbuifyscrumy.Role'),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='email',
            field=models.TextField(default='ogbuifymark@gmail.com'),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='user_name',
            field=models.TextField(default='mark'),
        ),
    ]
