# Generated by Django 2.0.2 on 2018-04-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogbuifyscrumy', '0002_auto_20180426_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='GoalStatus',
        ),
    ]
