# Generated by Django 2.0.2 on 2018-04-27 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogbuifyscrumy', '0003_auto_20180426_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoal',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 27, 12, 10, 57, 234114)),
        ),
        migrations.AddField(
            model_name='scrumygoal',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scrumygoal',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ogbuifyscrumy.Role'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogbuifyscrumy.ScrumyUser'),
        ),
        migrations.AddField(
            model_name='scrumygoal',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ogbuifyscrumy.Task'),
        ),
    ]
