# Generated by Django 2.0.2 on 2018-05-06 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ogbuifyscrumy', '0004_auto_20180427_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ogbuifyscrumy.GoalStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrumygoal',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scrumygoal',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='user_name',
            field=models.TextField(unique=True),
        ),
    ]
